services:
  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    ports:
      - "443:443"
    env_file: .env
    image: nginx
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    image: mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    env_file: 
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    expose:
      - "9000"
    image: wordpress

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ajoliet/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ajoliet/data/mariadb'

networks:
  inception:
    driver: bridge
